### ISSUE TITLE
OSK Not showing

### ISSUE THREAD

**Issue by davemcdermid** [MirServer/ubuntu-frame-osk#8] opened 2021-11-19 10:24 UTC
I've tried installing this on a Raspberry Pi 4B with a fresh ubuntu-server 20.04 install, with only ubuntu-frame & wpe-webkit-mir-kiosk (both on edge) also installed but I can't get the keyboard to show.

```
$ snap list
Name                  Version            Rev    Tracking       Publisher   Notes
core18                20211015           2248   latest/stable  canonical✓  base
core20                20211115           1244   latest/stable  canonical✓  base
lxd                   4.0.8              21843  4.0/stable/…   canonical✓  -
mesa-core20           21.0.3             96     latest/stable  canonical✓  -
snapd                 2.52.1             13643  latest/stable  canonical✓  snapd
ubuntu-frame          52-mir2.5.0+dev99  579    latest/edge    canonical✓  -
ubuntu-frame-osk      0+git.39f12a5      13     latest/edge    saviq       -
wpe-webkit-mir-kiosk  2.28.1             42     latest/edge    glancr      -

$ sudo snap logs ubuntu-frame-osk
2021-11-19T10:10:14Z systemd[1]: Stopping Service for snap application ubuntu-frame-osk.daemon...
2021-11-19T10:10:14Z ubuntu-frame-osk.daemon[5670]: Can't connect to the bus: Cannot autolaunch D-Bus without X11 $DISPLAY. Visibility switching unavailable.
2021-11-19T10:10:14Z systemd[1]: snap.ubuntu-frame-osk.daemon.service: Succeeded.
2021-11-19T10:10:14Z systemd[1]: Stopped Service for snap application ubuntu-frame-osk.daemon.
2021-11-19T10:10:14Z systemd[1]: Started Service for snap application ubuntu-frame-osk.daemon.
2021-11-19T10:10:14Z ubuntu-frame-osk.daemon[5813]: No keyboard layout specified
2021-11-19T10:10:15Z -[5813]: No system layout present
2021-11-19T10:10:15Z ubuntu-frame-osk.daemon[5813]: Debug: Tried file "/root/snap/ubuntu-frame-osk/13/.local/share/squeekboard/keyboards/us.yaml", but it's missing: No such file or directory (os error 2)
2021-11-19T10:10:15Z ubuntu-frame-osk.daemon[5813]: Info: Loaded layout Resource: us
2021-11-19T10:10:15Z -[5813]: Could not connect to session manager: Cannot autolaunch D-Bus without X11 $DISPLAY
```

I wondered if the problem was only a missing keyboard file, so I tried creating `us.yaml` manually and configuring the layout value to be the path, but this didn't help.

```
$ sudo snap set ubuntu-frame-osk layout=/var/opt/keyboards/us-keyboard.yaml

$ sudo snap logs ubuntu-frame-osk
2021-11-19T10:08:34Z ubuntu-frame-osk.daemon[5670]: Using keyboard layout /var/opt/keyboards/us-keyboard.yaml
2021-11-19T10:08:35Z ubuntu-frame-osk.daemon[5670]: Debug: Tried file "/var/opt/keyboards/us-keyboard.yaml", but it's missing: No such file or directory (os error 2)
2021-11-19T10:08:35Z ubuntu-frame-osk.daemon[5670]: Warning: Failed to load layout from Resource: /var/opt/keyboards/us-keyboard.yaml: Missing resource, skipping
2021-11-19T10:08:35Z ubuntu-frame-osk.daemon[5670]: Debug: Tried file "/root/snap/ubuntu-frame-osk/13/.local/share/squeekboard/keyboards/us.yaml", but it's missing: No such file or directory (os error 2)
2021-11-19T10:08:35Z ubuntu-frame-osk.daemon[5670]: Info: Loaded layout Resource: us
2021-11-19T10:08:35Z ubuntu-frame-osk.daemon[5670]: Debug: Tried file "/var/opt/keyboards/us-keyboard.yaml", but it's missing: No such file or directory (os error 2)
2021-11-19T10:08:35Z ubuntu-frame-osk.daemon[5670]: Warning: Failed to load layout from Resource: /var/opt/keyboards/us-keyboard.yaml: Missing resource, skipping
2021-11-19T10:08:35Z ubuntu-frame-osk.daemon[5670]: Debug: Tried file "/root/snap/ubuntu-frame-osk/13/.local/share/squeekboard/keyboards/us.yaml", but it's missing: No such file or directory (os error 2)
2021-11-19T10:08:35Z ubuntu-frame-osk.daemon[5670]: Info: Loaded layout Resource: us
2021-11-19T10:08:35Z -[5670]: Could not connect to session manager: Cannot autolaunch D-Bus without X11 $DISPLAY
```

**Comment by Saviq** [comment] 2021-11-19 11:27
Hi @davemcdermid, note that `/var/opt…` is not available to ubuntu-frame-osk due to snap confinement. You'd need to place it undeer`/root/snap/ubuntu-frame-osk/…` like you can see in the logs. That said, seeing as it then says "Info: Loaded layout Resource: us", I don't think that's the problem.

**Comment by davemcdermid** [comment] 2021-11-19 14:36
Ok, that makes sense, I guess it finds a layout file elsewhere. So the problem is more likely `Could not connect to session manager: Cannot autolaunch D-Bus without X11 $DISPLAY`. Any suggestions I can try to resolve this?

Thanks for you help

**Comment by wmww** [comment] 2021-11-19 15:04
What URL did you point wpe-webkit-mir-kiosk to?

**Comment by davemcdermid** [comment] 2021-11-19 15:58
I used https://google.com as it has a nice bit text field in the middle of the page.

**Comment by wmww** [comment] 2021-11-19 19:28
It sounds like Saviq has reproduced and we're investigating. I do not see this issue in a Core VM on x86,

**Comment by davemcdermid** [comment] 2021-11-19 19:35
Ah, great - thanks.

**Comment by wmww** [comment] 2021-11-19 20:46
I've inspected the logs, and it appears wpe-webkit-mir-kiosk does not even bind to the `zwp_text_input_manager_v3` global on ARM (unlike x86, where it correctly uses this protocol). I'm not sure why that would be, except if the ARM version is using an earlier version of *something* (I don't know enough about the architecture of `wpe-webkit-mir-kiosk` to speculate on what that might be).

**Comment by wmww** [comment] 2021-11-19 20:58
Ah! if you look at [the wpe-webkit-mir-kiosk snap page](https://snapcraft.io/wpe-webkit-mir-kiosk) and open the channel/version menu at the top you can switch architectures. You'll notice amd64 and armhf are all at 2.30.5 and published in October 2021, but arm64 is at lower versions (2.28.1 for edge) and published about a year ago. Don't know why that is, but it's almost certainly the cause. Some component must have been fixed in the last year to work with the text input protocol on Wayland, which is needed for the OSK.

**Comment by AlanGriffiths** [comment] 2021-11-19 20:59
On Fri, 19 Nov 2021 12:46:14 -0800, William Wold wrote:
> I've inspected the logs, and it appears wpe-webkit-mir-kiosk 
> does not even bind to the `zwp_text_input_manager_v3` global on 
> ARM (unlike x86, where it correctly uses this protocol). I'm not 
> sure why that would be, except if the ARM version is using an 
> earlier version of *something* (I don't know enough about the 
> architecture of `wpe-webkit-mir-kiosk` to speculate on what that 
> might be).

The arm64 version of wpe-webkit doesn't get updated. I think because of build issues. @Tobias will know more.

-- 
Sent using Dekko from my Ubuntu device

**Comment by wmww** [comment] 2021-11-19 21:00
Also, someone opened an issue for this yesterday: https://gitlab.com/glancr/wpe-webkit-snap/-/issues/31

**Comment by wmww** [comment] 2021-11-19 21:04
Due to the trouble and potentially expense of debugging inconsistencies across architectures, perhaps allowing some architectures to fall a year behind is a bad idea. If one architecture is failing, maybe don't update the others until it's fixed? Or completely remove it until it's fixed?

**Comment by wmww** [comment] 2021-12-16 17:30
Not an Ubuntu Frame OSK bug, see https://gitlab.com/glancr/wpe-webkit-snap/-/issues/31 for progress.

**Closed by wmww** 2021-12-16 17:30 UTC
